{{ config(materialized="view") }}

select
    {{ dbt_utils.surrogate_key(['state', 'year']) }} as eia_id,
    state,
    year,
    cast(week_1 as integer) as week_1,
    cast(week_2 as integer) as week_2,
    cast(week_3 as integer) as week_3,
    cast(week_4 as integer) as week_4,
    cast(week_5 as integer) as week_5,
    cast(week_6 as integer) as week_6,
    cast(week_7 as integer) as week_7,
    cast(week_8 as integer) as week_8,
    cast(week_9 as integer) as week_9,
    cast(week_10 as integer) as week_10,
    cast(week_11 as integer) as week_11,
    cast(week_12 as integer) as week_12,
    cast(week_13 as integer) as week_13,
    cast(week_14 as integer) as week_14,
    cast(week_15 as integer) as week_15,
    cast(week_16 as integer) as week_16,
    cast(week_17 as integer) as week_17,
    cast(week_18 as integer) as week_18,
    cast(week_19 as integer) as week_19,
    cast(week_20 as integer) as week_20,
    cast(week_21 as integer) as week_21,
    cast(week_22 as integer) as week_22,
    cast(week_23 as integer) as week_23,
    cast(week_24 as integer) as week_24,
    cast(week_25 as integer) as week_25,
    cast(week_26 as integer) as week_26,
    cast(week_27 as integer) as week_27,
    cast(week_28 as integer) as week_28,
    cast(week_29 as integer) as week_29,
    cast(week_30 as integer) as week_30,
    cast(week_31 as integer) as week_31,
    cast(week_32 as integer) as week_32,
    cast(week_33 as integer) as week_33,
    cast(week_34 as integer) as week_34,
    cast(week_35 as integer) as week_35,
    cast(week_36 as integer) as week_36,
    cast(week_37 as integer) as week_37,
    cast(week_38 as integer) as week_38,
    cast(week_39 as integer) as week_39,
    cast(week_40 as integer) as week_40,
    cast(week_41 as integer) as week_41,
    cast(week_42 as integer) as week_42,
    cast(week_43 as integer) as week_43,
    cast(week_44 as integer) as week_44,
    cast(week_45 as integer) as week_45,
    cast(week_46 as integer) as week_46,
    cast(week_47 as integer) as week_47,
    cast(week_48 as integer) as week_48,
    cast(week_49 as integer) as week_49,
    cast(week_50 as integer) as week_50,
    cast(week_51 as integer) as week_51,
    cast(week_52 as integer) as week_52,
    cast(week_53 as integer) as week_53,
    annual_average,
    annual_total,
    {{ categorize_state('state') }} as state_category
from {{ source('staging', 'eia_week') }}   